### ISSUE TITLE
Edx links not working

### ISSUE THREAD

**Issue by ostadomid** [minatafreshi/python-sandbox#1]
Correct links of the recommended video courses :

**Introduction to Python: Absolute Beginner**
https://www.edx.org/course/introduction-to-python-absolute-beginner-4

**Introduction to Computer Science and Programming Using Python**
https://www.edx.org/course/6-00-1x-introduction-to-computer-science-and-programming-using-python-3

**Comment by minatafreshi** [comment]
Hi Omid
As you pointed out, I'll edit these links soon as possible.
Thnaks for your response.
